project:
  type: website
  output-dir: docs

website:
  title: "Yiming | Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: experience.qmd
        text: Experience
      - href: projects.qmd
        text: Projects
      - href: visualization.qmd
        text: Visualizations
      - href: reflections.qmd
        text: Reflection

format:
  html:
    theme: cosmo
    css: style.css
    toc: true
    toc-depth: 3
